### PR TITLE
Check more

### LINKED ISSUE #130: CI does not cover all the options
The following options are being checked:
- empty, `alloc`, `defmt`, `esp-backtrace`, `log`, `unstable-hal`
We are missing:
- `wifi`, `ble`, `embassy`, `probe-rs`, `flashing-probe-rs/defmt`, `flashing-probe-rs/panic-rtt-target/`, `flashing-espflash/log`, `flashing-espflash/demft`, `flashing-espflash/esp-backtrace`

_Originally posted by @SergioGasquez in https://github.com/esp-rs/esp-generate/pull/129#discussion_r1963645227_

### PR DESCRIPTION
**Pull request by bjoernQ**
Closes #130

### CODE REVIEW

File: xtask/src/main.rs [hunk 1]
```diff
@@ -32,6 +36,9 @@ enum Commands {
         /// Actually build projects, instead of just checking them
         #[arg(short, long)]
         build: bool,
+        /// Just print what would be tested
+        #[arg(short, long)]
+        dry: bool,
```
Comment (SergioGasquez) [inline xtask/src/main.rs:41]: While doing some research for this same issue, I found out that we have an `options` subcommand that does mostly the same, was this on purpose?

**Review by SergioGasquez — APPROVED** [review]
LGTM! One small question

File: xtask/src/main.rs (hunk 1 above)
Comment (bjoernQ) [reply xtask/src/main.rs:41]: true it's definitely the same - personally, I would prefer `dry_run` and remove the `options` command (and rename `dry` to `dry_run`)

What do you think?

Comment (SergioGasquez) [reply xtask/src/main.rs:41]: Sounds good to me!
